name: qmmm
channels:
    - psi4
    - anaconda
dependencies:
    - python=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - sympy
    - IPython
    - jupyter
    - cython
    - scikit-learn
    - pip:
        - pyscf
        - autopep8
        - jupyter_contrib_nbextensions
        - scikit-optimize
    - psi4
    - cmake
